# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfsort < Formula
  desc "Sort Terraform files"
  homepage "https://github.com/AlexNabokikh/tfsort"
  version "0.2.2"

  on_macos do
    url "https://github.com/AlexNabokikh/tfsort/releases/download/v0.2.2/tfsort_0.2.2_darwin_all.tar.gz"
    sha256 "5f6da2295179fb6a55199eea4a172d512fed82512c98b1f96de4cecd88c55c75"

    def install
      bin.install "tfsort"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/AlexNabokikh/tfsort/releases/download/v0.2.2/tfsort_0.2.2_linux_armv6.tar.gz"
      sha256 "95ad33a2a57c24dc887e089737db36ad8245a708d9759589984caf646708a8e3"

      def install
        bin.install "tfsort"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AlexNabokikh/tfsort/releases/download/v0.2.2/tfsort_0.2.2_linux_amd64.tar.gz"
      sha256 "078aacaf2a55674e8ec31bec04f2f8ccc6c8c3420f1bb2728aa8654d86233356"

      def install
        bin.install "tfsort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexNabokikh/tfsort/releases/download/v0.2.2/tfsort_0.2.2_linux_arm64.tar.gz"
      sha256 "e54f0d05758e3835f21ee68574730efd1f1627a48fc7cb4c05c9a99c05cf6c20"

      def install
        bin.install "tfsort"
      end
    end
  end
end
